apiVersion: v1
kind: ReplicationController
metadata:
  name: weave-scope-app
  labels:
    provider: weave-scope-app
    heritage: helm
spec:
  replicas: 1
  template:
    metadata:
      labels:
        provider: weave-scope-app
    spec:
      containers:
      - name: weave-scope-app
        image: albanc/scope:latest
        args:
        - --no-probe
        ports:
        - containerPort: 4040
          hostPort: 4040
