apiVersion: v1
kind: Service
metadata:
  name: weave-scope-app
  labels:
    provider: weave-scope-app
    heritage: helm
spec:
  ports:
  - name: app
    port: 4040
  selector:
    provider: weave-scope-app
  clusterIP: 10.3.0.131
